---
- name: Disable SELinux
  selinux:
    state: disabled
  tags: selinux

- name: Run setenforce 0
  shell: setenforce 0
  ignore_errors: yes
  tags: selinux

- name: "Install EPEL repository"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest
  tags: utils, update, packages

- name: Install Nagios Plugins
  yum:
    name:
      - nagios-plugins-all
      - nrpe
    state: latest
  tags: packages


- name: Remove file /etc/nagios/nrpe.cfg
  file:
    path: /etc/nagios/nrpe.cfg
    state: absent

- name: Create nrpe configuration
  blockinfile:
    path: /etc/nagios/nrpe.cfg
    create: yes
    block: |
      log_facility=daemon
      debug=0
      pid_file=/var/run/nrpe/nrpe.pid
      server_port=5666
      nrpe_user=nrpe
      nrpe_group=nrpe
      allowed_hosts=192.168.0.1
      dont_blame_nrpe=1
      allow_bash_command_substitution=0
      command_timeout=60
      connection_timeout=300

      ### MISC SYSTEM METRICS ###
      command[check_users]=/usr/lib64/nagios/plugins/check_users $ARG1$
      command[check_load]=/usr/lib64/nagios/plugins/check_load $ARG1$
      command[check_disk]=/usr/lib64/nagios/plugins/check_disk $ARG1$
      command[check_swap]=/usr/lib64/nagios/plugins/check_swap $ARG1$
      command[check_cpu_stats]=/usr/lib64/nagios/plugins/check_cpu_stats.sh $ARG1$
      command[check_mem]=/usr/lib64/nagios/plugins/custom_check_mem -n $ARG1$
      command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs $ARG1$


      include_dir=/etc/nrpe.d/

- name: Start service nrpe
  service:
    name: nrpe
    state: started
    enabled: yes
  register: service_enable
  tags: service
