---
- hosts: all
  become: True
  gather_facts: True

  tasks:
  - include_tasks: common.yml

  - name: Install NGINX Server
    yum:
      name: nginx
      state: latest
    tags: packages

  - name: Enable service nginx
    service:
      name: nginx
      enabled: yes
    tags: service

  - name: Create configuration file /etc/nginx/conf.d/odoo.conf
    blockinfile:
      path: /etc/nginx/conf.d/odoo.conf
      create: yes
      block: |
        #odoo server
        upstream odoo {
         server 192.168.0.20:8069;
         server 192.168.0.21:8069;
         server 192.168.0.22:8069;
        }
        upstream odoochat {
         server 192.168.0.20:8072;
         server 192.168.0.21:8072;
         server 192.168.0.22:8072;
        }

        server {
           listen 80;
           server_name odoo.mycompany.com;
           rewrite ^(.*) https://$host$1 permanent;
        }

        server {
         listen 8069;
         server_name localhost;
         proxy_read_timeout 720s;
         proxy_connect_timeout 720s;
         proxy_send_timeout 720s;

         # Add Headers for odoo proxy mode
         proxy_set_header X-Forwarded-Host $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Real-IP $remote_addr;

         # log
         access_log /var/log/nginx/odoo.access.log;
         error_log /var/log/nginx/odoo.error.log;

         # Redirect longpoll requests to odoo longpolling port
         location /longpolling {
         proxy_pass http://odoochat;
         }

         # Redirect requests to odoo backend server
         location / {
           proxy_redirect off;
           proxy_pass http://odoo;
         }

         location ~* /web/static/ {
           proxy_cache_valid 200 90m;
           proxy_buffering    on;
           expires 864000;
           proxy_pass http://odoo;
         }
         # common gzip
         gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
         gzip on;
        }

  - name: Start service nginx
    service:
      name: nginx
      state: started
      enabled: yes
    register: service_enable
    tags: service
